
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pwd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pwd'
    command: mysqld --sql_mode=""
    volumes:
      - ./db/parser-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  aws:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ACCESS_KEY_ID=test
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566:4566'
    volumes:
      - "./infra:/opt/infra"

volumes:
  cache:
    driver: local